//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.JxcServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yh_jinxiaocun_excelEntities3 : DbContext
    {
        public yh_jinxiaocun_excelEntities3()
            : base("name=yh_jinxiaocun_excelEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<yh_jinxiaocun_chanpin_mssql> yh_jinxiaocun_chanpin_mssql { get; set; }
        public DbSet<yh_jinxiaocun_chuhuofang_mssql> yh_jinxiaocun_chuhuofang_mssql { get; set; }
        public DbSet<yh_jinxiaocun_jichuziliao_mssql> yh_jinxiaocun_jichuziliao_mssql { get; set; }
        public DbSet<yh_jinxiaocun_jinhuofang_mssql> yh_jinxiaocun_jinhuofang_mssql { get; set; }
        public DbSet<yh_jinxiaocun_kucun_mssql> yh_jinxiaocun_kucun_mssql { get; set; }
        public DbSet<yh_jinxiaocun_mingxi_mssql> yh_jinxiaocun_mingxi_mssql { get; set; }
        public DbSet<yh_jinxiaocun_qichushu_mssql> yh_jinxiaocun_qichushu_mssql { get; set; }
        public DbSet<yh_jinxiaocun_user_mssql> yh_jinxiaocun_user_mssql { get; set; }
        public DbSet<yh_jinxiaocun_yongliaosheding_mssql> yh_jinxiaocun_yongliaosheding_mssql { get; set; }
        public DbSet<yh_jinxiaocun_zhengli_mssql> yh_jinxiaocun_zhengli_mssql { get; set; }
    }
}
