//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.JxcServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_jinxiaocun_mingxi_mssql
    {
        public int C_id { get; set; }
        public string C_openid { get; set; }
        public string cpid { get; set; }
        public string cpjj { get; set; }
        public string cplb { get; set; }
        public string cpname { get; set; }
        public string cpsj { get; set; }
        public string cpsl { get; set; }
        public string finduser { get; set; }
        public string gongsi { get; set; }
        public string mxtype { get; set; }
        public string orderid { get; set; }
        public Nullable<System.DateTime> shijian { get; set; }
        public string sp_dm { get; set; }
        public string shou_h { get; set; }
        public string zh_name { get; set; }
        public string gs_name { get; set; }
    }
}
