//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.JxcServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_jinxiaocun_user_mssql
    {
        public string _id { get; set; }
        public string AdminIS { get; set; }
        public string Btype { get; set; }
        public string Createdate { get; set; }
        public string _openid { get; set; }
        public string gongsi { get; set; }
        public string jigoudaima { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string mi_bao { get; set; }
        public string _id1 { get; set; }
        public string wechart_user { get; set; }
        public string touxiang { get; set; }
        public string shujuku { get; set; }
    }
}
