//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_manage
    {
        public int id { get; set; }
        public string contract_code { get; set; }
        public string contract_name { get; set; }
        public string contract_type { get; set; }
        public string first_party { get; set; }
        public string second_party { get; set; }
        public string creator { get; set; }
        public string creation_date { get; set; }
        public string send_out { get; set; }
        public string company { get; set; }
        public string send_judge { get; set; }
    }
}
