//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_personnel_power
    {
        public int id { get; set; }
        public string personnel_id { get; set; }
        public string gerenzhongxin_sel { get; set; }
        public string gerenzhongxin_upd { get; set; }
        public string hetongguanli_sel { get; set; }
        public string hetongguanli_del { get; set; }
        public string hetongguanli_upd { get; set; }
        public string hetongguanli_add { get; set; }
        public string zhanghuzhongxin_sel { get; set; }
        public string zhanghuzhongxin_del { get; set; }
        public string zhanghuzhongxin_upd { get; set; }
        public string zhanghuzhongxin_add { get; set; }
        public string yinzhangguanli_sel { get; set; }
        public string yinzhangguanli_del { get; set; }
        public string yinzhangguanli_upd { get; set; }
        public string yinzhangguanli_add { get; set; }
        public string hetongguanli_dow { get; set; }
    }
}
