//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceEntities : DbContext
    {
        public FinanceEntities()
            : base("name=FinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Accounting> Accounting { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<FinancingExpenditure> FinancingExpenditure { get; set; }
        public DbSet<FinancingIncome> FinancingIncome { get; set; }
        public DbSet<InvestmentExpenditure> InvestmentExpenditure { get; set; }
        public DbSet<InvestmentIncome> InvestmentIncome { get; set; }
        public DbSet<ManagementExpenditure> ManagementExpenditure { get; set; }
        public DbSet<ManagementIncome> ManagementIncome { get; set; }
        public DbSet<SimpleAccounting> SimpleAccounting { get; set; }
        public DbSet<SimpleData> SimpleData { get; set; }
        public DbSet<VoucherSummary> VoucherSummary { get; set; }
        public DbSet<VoucherWord> VoucherWord { get; set; }
    }
}
