//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzimingxi
    {
        public int id { get; set; }
        public string renming { get; set; }
        public Nullable<System.DateTime> shijian { get; set; }
        public string ticheng { get; set; }
        public string xiaoshoushuliang { get; set; }
        public string xiaoshoujine { get; set; }
        public string chanpinchengben { get; set; }
        public string yinhangzhanghu { get; set; }
        public Nullable<decimal> koukuan { get; set; }
        public Nullable<decimal> gongzi { get; set; }
        public Nullable<decimal> yifu { get; set; }
        public string beizhu { get; set; }
        public string company { get; set; }
        public Nullable<decimal> kkqgongzi { get; set; }
    }
}
