//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public string type { get; set; }
        public string riqi { get; set; }
        public string zhaiyao { get; set; }
        public string unit { get; set; }
        public string invoice_type { get; set; }
        public string invoice_no { get; set; }
        public string jine { get; set; }
        public string remarks { get; set; }
        public string company { get; set; }
    }
}
