//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanxian
    {
        public int id { get; set; }
        public string kmzz_add { get; set; }
        public string kmzz_delete { get; set; }
        public string kmzz_update { get; set; }
        public string kmzz_select { get; set; }
        public string kzxm_add { get; set; }
        public string kzxm_delete { get; set; }
        public string kzxm_update { get; set; }
        public string kzxm_select { get; set; }
        public string bmsz_add { get; set; }
        public string bmsz_delete { get; set; }
        public string bmsz_update { get; set; }
        public string bmsz_select { get; set; }
        public string pzhz_add { get; set; }
        public string pzhz_delete { get; set; }
        public string pzhz_update { get; set; }
        public string pzhz_select { get; set; }
        public string znkb_select { get; set; }
        public string xjll_select { get; set; }
        public string zcfz_select { get; set; }
        public string lysy_select { get; set; }
        public string jjtz_add { get; set; }
        public string jjtz_delete { get; set; }
        public string jjtz_update { get; set; }
        public string jjtz_select { get; set; }
        public string jjzz_add { get; set; }
        public string jjzz_delete { get; set; }
        public string jjzz_update { get; set; }
        public string jjzz_select { get; set; }
        public string zhgl_add { get; set; }
        public string zhgl_delete { get; set; }
        public string zhgl_update { get; set; }
        public string zhgl_select { get; set; }
        public string bianhao { get; set; }
    }
}
