//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleData
    {
        public int id { get; set; }
        public string company { get; set; }
        public string project { get; set; }
        public Nullable<decimal> receivable { get; set; }
        public Nullable<decimal> receipts { get; set; }
        public Nullable<decimal> cope { get; set; }
        public Nullable<decimal> payment { get; set; }
        public string accounting { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string kehu { get; set; }
        public string zhaiyao { get; set; }
        public Nullable<decimal> nashuijine { get; set; }
        public Nullable<decimal> yijiaoshuijine { get; set; }
    }
}
