//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherSummary
    {
        public int id { get; set; }
        public string word { get; set; }
        public string no { get; set; }
        public string @abstract { get; set; }
        public string code { get; set; }
        public string department { get; set; }
        public string expenditure { get; set; }
        public string note { get; set; }
        public string man { get; set; }
        public Nullable<decimal> money { get; set; }
        public string company { get; set; }
        public Nullable<System.DateTime> voucherDate { get; set; }
        public Nullable<decimal> real { get; set; }
    }
}
