//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int code { get; set; }
        public string name { get; set; }
        public bool direction { get; set; }
        public Nullable<decimal> load { get; set; }
        public Nullable<decimal> borrowed { get; set; }
        public int id { get; set; }
        public string company { get; set; }
    }
}
