//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_manage
    {
        public int id { get; set; }
        public string contract_code { get; set; }
        public string contract_name { get; set; }
        public string contract_type { get; set; }
        public string first_party { get; set; }
        public string second_party { get; set; }
        public string creator { get; set; }
        public string creation_date { get; set; }
        public string send_out { get; set; }
        public string company { get; set; }
        public string send_judge { get; set; }
    }
}
