//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_soft_time
    {
        public int C_id { get; set; }
        public string name { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public string soft_name { get; set; }
        public string denglushijian { get; set; }
        public string password { get; set; }
        public string pid { get; set; }
        public string mark1 { get; set; }
        public string mark2 { get; set; }
        public string mark3 { get; set; }
        public string mark4 { get; set; }
        public string mark5 { get; set; }
    }
}
