//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_personnel_power
    {
        public int id { get; set; }
        public string personnel_id { get; set; }
        public string gerenzhongxin_sel { get; set; }
        public string gerenzhongxin_upd { get; set; }
        public string hetongguanli_sel { get; set; }
        public string hetongguanli_del { get; set; }
        public string hetongguanli_upd { get; set; }
        public string hetongguanli_add { get; set; }
        public string zhanghuzhongxin_sel { get; set; }
        public string zhanghuzhongxin_del { get; set; }
        public string zhanghuzhongxin_upd { get; set; }
        public string zhanghuzhongxin_add { get; set; }
        public string yinzhangguanli_sel { get; set; }
        public string yinzhangguanli_del { get; set; }
        public string yinzhangguanli_upd { get; set; }
        public string yinzhangguanli_add { get; set; }
        public string hetongguanli_dow { get; set; }
    }
}
