//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public string type { get; set; }
        public string riqi { get; set; }
        public string zhaiyao { get; set; }
        public string unit { get; set; }
        public string invoice_type { get; set; }
        public string invoice_no { get; set; }
        public string jine { get; set; }
        public string remarks { get; set; }
        public string company { get; set; }
    }
}
