//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleData
    {
        public int id { get; set; }
        public string company { get; set; }
        public string project { get; set; }
        public Nullable<decimal> receivable { get; set; }
        public Nullable<decimal> receipts { get; set; }
        public Nullable<decimal> cope { get; set; }
        public Nullable<decimal> payment { get; set; }
        public string accounting { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string kehu { get; set; }
        public string zhaiyao { get; set; }
    }
}
