//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.finance.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherSummary
    {
        public int id { get; set; }
        public string word { get; set; }
        public string no { get; set; }
        public string @abstract { get; set; }
        public int code { get; set; }
        public string department { get; set; }
        public string expenditure { get; set; }
        public string note { get; set; }
        public string man { get; set; }
        public Nullable<decimal> money { get; set; }
        public string company { get; set; }
        public Nullable<System.DateTime> voucherDate { get; set; }
        public Nullable<decimal> real { get; set; }
    }
}
