//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_jinxiaocun_chuhuofang
    {
        public string C_openid { get; set; }
        public string beizhu { get; set; }
        public string finduser { get; set; }
        public string gongsi { get; set; }
        public string lianxidizhi { get; set; }
        public string lianxifangshi { get; set; }
        public int _id { get; set; }
    }
}
