//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_jinxiaocun_jichuziliao
    {
        public string sp_dm { get; set; }
        public string name { get; set; }
        public string lei_bie { get; set; }
        public string dan_wei { get; set; }
        public string shou_huo { get; set; }
        public string gong_huo { get; set; }
        public int id { get; set; }
        public string zh_name { get; set; }
        public string gs_name { get; set; }
        public string mark1 { get; set; }
    }
}
