//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int id { get; set; }
        public string department_name { get; set; }
        public string add { get; set; }
        public string del { get; set; }
        public string upd { get; set; }
        public string sel { get; set; }
        public string view_name { get; set; }
        public string company { get; set; }
    }
}
