//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int id { get; set; }
        public string department_name { get; set; }
        public string add { get; set; }
        public string del { get; set; }
        public string upd { get; set; }
        public string sel { get; set; }
        public string view_name { get; set; }
        public string company { get; set; }
    }
}
