//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_check
    {
        public int id { get; set; }
        public string order_number { get; set; }
        public string moudle { get; set; }
        public string riqi { get; set; }
        public Nullable<double> num { get; set; }
        public string company { get; set; }
    }
}
