//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_info
    {
        public int id { get; set; }
        public string code { get; set; }
        public string product_name { get; set; }
        public string norms { get; set; }
        public string order_id { get; set; }
        public Nullable<System.DateTime> set_date { get; set; }
        public int set_num { get; set; }
        public string company { get; set; }
    }
}
