//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paibanbiao_renyuan
    {
        public int id { get; set; }
        public string staff_name { get; set; }
        public string phone_number { get; set; }
        public string banci { get; set; }
        public string department_name { get; set; }
        public string id_number { get; set; }
        public string company { get; set; }
        public string b { get; set; }
        public string c { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string f { get; set; }
        public string g { get; set; }
        public string h { get; set; }
        public string i { get; set; }
        public string j { get; set; }
        public string k { get; set; }
        public string l { get; set; }
        public string m { get; set; }
        public string n { get; set; }
    }
}
