//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paibanbiao_info
    {
        public int id { get; set; }
        public Nullable<int> paibanbiao_detail_id { get; set; }
        public string riqi { get; set; }
        public string renshu { get; set; }
        public string plan_name { get; set; }
        public string department_name { get; set; }
        public string remarks1 { get; set; }
        public string remarks2 { get; set; }
        public string remarks3 { get; set; }
        public string remarks4 { get; set; }
        public string remarks5 { get; set; }
    }
}
