//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schedulingEntities : DbContext
    {
        public schedulingEntities()
            : base("name=schedulingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<module_info> module_info { get; set; }
        public DbSet<module_type> module_type { get; set; }
        public DbSet<user_info> user_info { get; set; }
        public DbSet<holiday_config> holiday_config { get; set; }
        public DbSet<time_config> time_config { get; set; }
        public DbSet<bom_info> bom_info { get; set; }
        public DbSet<order_bom> order_bom { get; set; }
        public DbSet<order_info> order_info { get; set; }
        public DbSet<work_detail> work_detail { get; set; }
        public DbSet<work_module> work_module { get; set; }
    }
}
