//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_config
    {
        public int id { get; set; }
        public Nullable<int> week { get; set; }
        public string morning_start { get; set; }
        public string morning_end { get; set; }
        public string noon_start { get; set; }
        public string noon_end { get; set; }
        public string night_start { get; set; }
        public string night_end { get; set; }
        public string company { get; set; }
    }
}
