//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_detail1
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> work_num { get; set; }
        public Nullable<System.DateTime> work_start_date { get; set; }
        public string company { get; set; }
        public Nullable<int> row_num { get; set; }
        public Nullable<int> is_insert { get; set; }
    }
}
