//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.scheduling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_detail2
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int work_num { get; set; }
        public System.DateTime work_start_date { get; set; }
        public string company { get; set; }
        public Nullable<int> row_num { get; set; }
        public Nullable<int> is_insert { get; set; }
    }
}
