//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerEntities : DbContext
    {
        public ServerEntities()
            : base("name=ServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<yh_jinxiaocun_chanpin> yh_jinxiaocun_chanpin { get; set; }
        public DbSet<yh_jinxiaocun_chuhuofang> yh_jinxiaocun_chuhuofang { get; set; }
        public DbSet<yh_jinxiaocun_chuhuofang1> yh_jinxiaocun_chuhuofang1 { get; set; }
        public DbSet<yh_jinxiaocun_jichuziliao> yh_jinxiaocun_jichuziliao { get; set; }
        public DbSet<yh_jinxiaocun_jinhuofang> yh_jinxiaocun_jinhuofang { get; set; }
        public DbSet<yh_jinxiaocun_jinhuofang1> yh_jinxiaocun_jinhuofang1 { get; set; }
        public DbSet<yh_jinxiaocun_kucun> yh_jinxiaocun_kucun { get; set; }
        public DbSet<yh_jinxiaocun_mingxi> yh_jinxiaocun_mingxi { get; set; }
        public DbSet<yh_jinxiaocun_qichushu> yh_jinxiaocun_qichushu { get; set; }
        public DbSet<yh_jinxiaocun_user> yh_jinxiaocun_user { get; set; }
        public DbSet<yh_jinxiaocun_yongliaosheding> yh_jinxiaocun_yongliaosheding { get; set; }
        public DbSet<yh_jinxiaocun_zhengli> yh_jinxiaocun_zhengli { get; set; }
    }
}
