//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_jinxiaocun_yongliaosheding
    {
        public string name { get; set; }
        public string sp_dm { get; set; }
        public string yuan_liao_name { get; set; }
        public string yuan_liao_sl { get; set; }
        public int id { get; set; }
        public string yl_tx { get; set; }
        public string zh_name { get; set; }
        public string gs_name { get; set; }
    }
}
