//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class baitaoquanxian_copy2
    {
        public int id { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public string F { get; set; }
        public string G { get; set; }
        public string H { get; set; }
        public string I { get; set; }
        public string J { get; set; }
        public string K { get; set; }
        public string L { get; set; }
        public string M { get; set; }
        public string N { get; set; }
        public string O { get; set; }
        public string P { get; set; }
        public string Q { get; set; }
        public string R { get; set; }
        public string S { get; set; }
        public string T { get; set; }
        public string U { get; set; }
        public string V { get; set; }
        public string W { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public string AA { get; set; }
        public string AB { get; set; }
        public string AC { get; set; }
        public string AD { get; set; }
        public string AE { get; set; }
        public string AF { get; set; }
        public string AG { get; set; }
        public string AH { get; set; }
        public string AI { get; set; }
        public string AJ { get; set; }
        public string AK { get; set; }
        public string AL { get; set; }
        public string AM { get; set; }
        public string AN { get; set; }
        public string AO { get; set; }
        public string AP { get; set; }
        public string AQ { get; set; }
        public string AR { get; set; }
        public string ASS { get; set; }
        public string AT { get; set; }
        public string AU { get; set; }
        public string AV { get; set; }
        public string AW { get; set; }
        public string AX { get; set; }
        public string AY { get; set; }
        public string AZ { get; set; }
        public string BA { get; set; }
        public string BB { get; set; }
        public string BC { get; set; }
        public string BD { get; set; }
        public string BE { get; set; }
        public string BF { get; set; }
        public string BG { get; set; }
        public string BH { get; set; }
        public string BI { get; set; }
        public string BJ { get; set; }
        public string BK { get; set; }
        public string BL { get; set; }
        public string BM { get; set; }
        public string BN { get; set; }
        public string BO { get; set; }
        public string BP { get; set; }
        public string BQ { get; set; }
        public string BR { get; set; }
        public string BS { get; set; }
        public string BT { get; set; }
        public string BU { get; set; }
        public string BV { get; set; }
        public string BW { get; set; }
        public string BX { get; set; }
        public string BYY { get; set; }
        public string BZ { get; set; }
        public string CA { get; set; }
        public string CB { get; set; }
        public string CC { get; set; }
        public string CD { get; set; }
        public string CE { get; set; }
        public string CF { get; set; }
        public string CG { get; set; }
        public string CH { get; set; }
        public string CI { get; set; }
        public string CJ { get; set; }
        public string CK { get; set; }
        public string CL { get; set; }
        public string CM { get; set; }
        public string CN { get; set; }
        public string CO { get; set; }
        public string CP { get; set; }
        public string CQ { get; set; }
        public string CR { get; set; }
        public string CS { get; set; }
        public string CT { get; set; }
        public string CU { get; set; }
        public string CV { get; set; }
        public string 公司 { get; set; }
    }
}
