//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_shenpi
    {
        public int id { get; set; }
        public string name { get; set; }
        public string shifa_gongzi { get; set; }
        public string geren_zhichu { get; set; }
        public string qiye_zhichu { get; set; }
        public string yuangong_renshu { get; set; }
        public string quanqin_tianshu { get; set; }
        public string shenpiren { get; set; }
        public string riqi { get; set; }
    }
}
