//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_shezhi
    {
        public int id { get; set; }
        public string gongsi { get; set; }
        public string shezhi { get; set; }
        public string yi { get; set; }
        public string er { get; set; }
    }
}
