//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_renyuanManager
    {
        public int R_id { get; set; }
        public int add { get; set; }
        public int del { get; set; }
        public int upd { get; set; }
        public int sel { get; set; }
        public int look { get; set; }
        public int view_id { get; set; }
    }
}
