//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Pushnews.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_pushnews
    {
        public int id { get; set; }
        public string gsname { get; set; }
        public string xtname { get; set; }
        public string tpname1 { get; set; }
        public string tptop1 { get; set; }
        public string tpname2 { get; set; }
        public string tptop2 { get; set; }
        public string tpname3 { get; set; }
        public string tptop3 { get; set; }
        public string tpname4 { get; set; }
        public string tptop4 { get; set; }
        public string tpname5 { get; set; }
        public string tptop5 { get; set; }
        public string tpname6 { get; set; }
        public string tptop6 { get; set; }
        public string topkuan { get; set; }
        public string topgao { get; set; }
        public string xuankuan { get; set; }
        public string xuangao { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string textbox { get; set; }
        public string beizhu1 { get; set; }
        public string beizhu2 { get; set; }
        public string beizhu3 { get; set; }
        public string beizhu4 { get; set; }
        public string beizhu5 { get; set; }
        public string beizhu6 { get; set; }
        public string beizhu7 { get; set; }
        public string beizhu8 { get; set; }
        public string beizhu9 { get; set; }
        public string beizhu10 { get; set; }
        public Nullable<System.DateTime> qidate { get; set; }
        public Nullable<System.DateTime> zhidate { get; set; }
    }
}
