//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class baitaoquanxian_renyun
    {
        public int id { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public string renyuan_id { get; set; }
        public string zhuangtai { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string bianhao { get; set; }
        public string quanxian_id { get; set; }
        public string bumen { get; set; }
        public string wechart_user { get; set; }
        public string touxiang { get; set; }
    }
}
