//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_gongzuoshijian
    {
        public int id { get; set; }
        public string gongzuoshijianks { get; set; }
        public string gongzuoshijianjs { get; set; }
        public string wuxiushijianks { get; set; }
        public string wuxiushijianjs { get; set; }
        public string year_month { get; set; }
        public string riqi { get; set; }
        public string gongsi { get; set; }
        public string work_days { get; set; }
        public string repeat_type { get; set; }
        public string schedule_title { get; set; }
        public string schedule_status { get; set; }
        public string repeat_end_date { get; set; }
    }
}
