//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_renyuanManager
    {
        public int R_id { get; set; }
        public int add { get; set; }
        public int del { get; set; }
        public int upd { get; set; }
        public int sel { get; set; }
        public int look { get; set; }
        public int view_id { get; set; }
    }
}
