//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_peizhi
    {
        public string gongsi { get; set; }
        public string kaoqin { get; set; }
        public string kaoqin_peizhi { get; set; }
        public string bumen { get; set; }
        public string zhiwu { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public int id { get; set; }
        public string chidao_koukuan { get; set; }
        public string geren_yiliao { get; set; }
        public string qiye_yiliao { get; set; }
        public string geren_shengyu { get; set; }
        public string qiye_shengyu { get; set; }
        public string geren_gongjijin { get; set; }
        public string qiye_gongjijin { get; set; }
        public string yiliao_jishu { get; set; }
        public string geren_nianjin { get; set; }
        public string zhinajin { get; set; }
        public string nianjin_jishu { get; set; }
        public string lixi { get; set; }
        public string jixiao_gongzi { get; set; }
        public string geren_yanglao { get; set; }
        public string qiye_yanglao { get; set; }
        public string gangwei { get; set; }
        public string gangwei_gongzi { get; set; }
        public string qiye_shiye { get; set; }
        public string gongzi { get; set; }
        public string shuilv { get; set; }
        public string kuadu_gongzi { get; set; }
        public string qiye_gongshang { get; set; }
        public string jintie { get; set; }
        public string qiye_nianjin { get; set; }
        public string nianjin1 { get; set; }
        public string jiabanfei { get; set; }
        public string yansuangongshi { get; set; }
        public string queqin_koukuan { get; set; }
        public string geren_shiye { get; set; }
    }
}
