//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_peizhi
    {
        public string gongsi { get; set; }
        public string kaoqin { get; set; }
        public string kaoqin_peizhi { get; set; }
        public string bumen { get; set; }
        public string zhiwu { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public int id { get; set; }
    }
}
