//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_jianliguanli
    {
        public int id { get; set; }
        public string touliren { get; set; }
        public string xueli { get; set; }
        public string mubiaogangwei { get; set; }
        public string tijiaoshijian { get; set; }
        public string beizhu { get; set; }
        public string gongsi { get; set; }
        public string wenjian { get; set; }
        public string zhuangtai { get; set; }
        public string mianshipizhu { get; set; }
    }
}
