//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gongzi_lizhishenpi
    {
        public int id { get; set; }
        public string bumen { get; set; }
        public string xingming { get; set; }
        public string tijiaoriqi { get; set; }
        public string shenqingyuanyin { get; set; }
        public string shenpijieguo { get; set; }
        public string shenpiyuanyin { get; set; }
        public string gongsi { get; set; }
    }
}
