//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yaoEntities : DbContext
    {
        public yaoEntities()
            : base("name=yaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gongzi_gongzimingxi> gongzi_gongzimingxi { get; set; }
        public DbSet<gongzi_kaoqinjilu> gongzi_kaoqinjilu { get; set; }
        public DbSet<gongzi_kaoqinmingxi> gongzi_kaoqinmingxi { get; set; }
        public DbSet<gongzi_peizhi> gongzi_peizhi { get; set; }
        public DbSet<gongzi_renyuan> gongzi_renyuan { get; set; }
        public DbSet<gongzi_renyuanManager> gongzi_renyuanManager { get; set; }
        public DbSet<gongzi_shezhi> gongzi_shezhi { get; set; }
        public DbSet<gongzi_viewNames> gongzi_viewNames { get; set; }
    }
}
