//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yaoEntities : DbContext
    {
        public yaoEntities()
            : base("name=yaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gongzi_gongzimingxi> gongzi_gongzimingxi { get; set; }
        public DbSet<gongzi_kaoqinjilu> gongzi_kaoqinjilu { get; set; }
        public DbSet<gongzi_kaoqinmingxi> gongzi_kaoqinmingxi { get; set; }
        public DbSet<gongzi_peizhi> gongzi_peizhi { get; set; }
        public DbSet<gongzi_renyuan> gongzi_renyuan { get; set; }
        public DbSet<gongzi_renyuanManager> gongzi_renyuanManager { get; set; }
        public DbSet<gongzi_shezhi> gongzi_shezhi { get; set; }
        public DbSet<gongzi_viewNames> gongzi_viewNames { get; set; }
        public DbSet<bainiantiantianmumen> bainiantiantianmumen { get; set; }
        public DbSet<bainiantiantianmumenmubiao> bainiantiantianmumenmubiao { get; set; }
        public DbSet<bainiantiantianmumenrenyuan> bainiantiantianmumenrenyuan { get; set; }
        public DbSet<baitaoquanxian> baitaoquanxian { get; set; }
        public DbSet<baitaoquanxian_copy1> baitaoquanxian_copy1 { get; set; }
        public DbSet<baitaoquanxian_copy2> baitaoquanxian_copy2 { get; set; }
        public DbSet<baitaoquanxian_gongsi> baitaoquanxian_gongsi { get; set; }
        public DbSet<baitaoquanxian_renyun> baitaoquanxian_renyun { get; set; }
        public DbSet<dearhylo9_cangku> dearhylo9_cangku { get; set; }
        public DbSet<dearhylo9_jiandan> dearhylo9_jiandan { get; set; }
        public DbSet<dearhylo9_renyuan> dearhylo9_renyuan { get; set; }
        public DbSet<dearhylo9_tuihuo> dearhylo9_tuihuo { get; set; }
        public DbSet<kaozhiguang147852> kaozhiguang147852 { get; set; }
        public DbSet<kaozhiguang147852_gongzi> kaozhiguang147852_gongzi { get; set; }
        public DbSet<kaozhiguang147852_jiben> kaozhiguang147852_jiben { get; set; }
        public DbSet<kaozhiguang147852_jixie> kaozhiguang147852_jixie { get; set; }
        public DbSet<kaozhiguang147852_sika> kaozhiguang147852_sika { get; set; }
        public DbSet<liuchanglin_chanpinguanli> liuchanglin_chanpinguanli { get; set; }
        public DbSet<liuchanglin_chanpinxinxi> liuchanglin_chanpinxinxi { get; set; }
        public DbSet<liuchanglin_chuku> liuchanglin_chuku { get; set; }
        public DbSet<liuchanglin_fuzhu> liuchanglin_fuzhu { get; set; }
        public DbSet<liuchanglin_gongyingshang> liuchanglin_gongyingshang { get; set; }
        public DbSet<liuchanglin_kehu> liuchanglin_kehu { get; set; }
        public DbSet<liuchanglin_kucun> liuchanglin_kucun { get; set; }
        public DbSet<liuchanglin_mingxi> liuchanglin_mingxi { get; set; }
        public DbSet<liuchanglin_mingxiguanli> liuchanglin_mingxiguanli { get; set; }
        public DbSet<liuchanglin_renyuan> liuchanglin_renyuan { get; set; }
        public DbSet<lv_al> lv_al { get; set; }
        public DbSet<lv_bcd> lv_bcd { get; set; }
        public DbSet<lv_td> lv_td { get; set; }
        public DbSet<lv_xhjr> lv_xhjr { get; set; }
        public DbSet<tb846607026_cunkuan> tb846607026_cunkuan { get; set; }
        public DbSet<tb846607026_jibie> tb846607026_jibie { get; set; }
        public DbSet<tb846607026_jine> tb846607026_jine { get; set; }
        public DbSet<tb846607026_peizhi> tb846607026_peizhi { get; set; }
        public DbSet<tb846607026_shouyi> tb846607026_shouyi { get; set; }
        public DbSet<tb846607026_tixian> tb846607026_tixian { get; set; }
        public DbSet<wodeliangnianfa_chukubiao> wodeliangnianfa_chukubiao { get; set; }
        public DbSet<wodeliangnianfa_gongyingshangxinxi> wodeliangnianfa_gongyingshangxinxi { get; set; }
        public DbSet<wodeliangnianfa_kehuxinxi> wodeliangnianfa_kehuxinxi { get; set; }
        public DbSet<wodeliangnianfa_kucun> wodeliangnianfa_kucun { get; set; }
        public DbSet<wodeliangnianfa_peizhibiao> wodeliangnianfa_peizhibiao { get; set; }
        public DbSet<wodeliangnianfa_renyaunxinxi> wodeliangnianfa_renyaunxinxi { get; set; }
        public DbSet<wodeliangnianfa_rukubiao> wodeliangnianfa_rukubiao { get; set; }
        public DbSet<wodeliangnianfa_shangpinxinxi> wodeliangnianfa_shangpinxinxi { get; set; }
        public DbSet<wodeliangnianfa_tuihuobiao> wodeliangnianfa_tuihuobiao { get; set; }
        public DbSet<wodeliangnianfa_xiadan> wodeliangnianfa_xiadan { get; set; }
        public DbSet<wodeliangnianfa_zhanghu> wodeliangnianfa_zhanghu { get; set; }
        public DbSet<zeng_stock> zeng_stock { get; set; }
        public DbSet<zeng_user> zeng_user { get; set; }
        public DbSet<zeng_wares> zeng_wares { get; set; }
        public DbSet<zhangfengliang2025_daili> zhangfengliang2025_daili { get; set; }
        public DbSet<zhangfengliang2025_jishiben> zhangfengliang2025_jishiben { get; set; }
        public DbSet<zhangfengliang2025_kucun> zhangfengliang2025_kucun { get; set; }
        public DbSet<zhangfengliang2025_mingxi> zhangfengliang2025_mingxi { get; set; }
        public DbSet<zhangfengliang2025_renyuanguanli> zhangfengliang2025_renyuanguanli { get; set; }
        public DbSet<zhangfengliang2025_rukumingxi> zhangfengliang2025_rukumingxi { get; set; }
        public DbSet<zhaobiaodailhuizong> zhaobiaodailhuizong { get; set; }
        public DbSet<zheng_020826_config> zheng_020826_config { get; set; }
        public DbSet<zheng_020826_gameInfo> zheng_020826_gameInfo { get; set; }
        public DbSet<zheng_020826_model> zheng_020826_model { get; set; }
        public DbSet<zheng_020826_userInfo> zheng_020826_userInfo { get; set; }
        public DbSet<gongzi_shenpi> gongzi_shenpi { get; set; }
    }
}
