//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kaozhiguang147852
    {
        public int id { get; set; }
        public string name { get; set; }
        public string xiangmu { get; set; }
        public string jieduan { get; set; }
        public string zhanghao { get; set; }
        public string mi { get; set; }
    }
}
