//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_stock
    {
        public string productCode { get; set; }
        public Nullable<double> discount { get; set; }
        public string direction { get; set; }
        public string userName { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int id { get; set; }
        public string comment { get; set; }
        public string payType { get; set; }
        public string order_id { get; set; }
    }
}
