//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_wares
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id { get; set; }
        public Nullable<int> num { get; set; }
        public string cloth { get; set; }
        public string norms { get; set; }
        public string type { get; set; }
        public string mark1 { get; set; }
        public string mark2 { get; set; }
        public string mark3 { get; set; }
        public string mark4 { get; set; }
        public string mark5 { get; set; }
    }
}
