//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_stock
    {
        public string productCode { get; set; }
        public Nullable<double> discount { get; set; }
        public string direction { get; set; }
        public string userName { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int id { get; set; }
        public string comment { get; set; }
        public string payType { get; set; }
        public string order_id { get; set; }
    }
}
