//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_user
    {
        public string userName { get; set; }
        public string password { get; set; }
        public string power { get; set; }
        public string shop { get; set; }
        public int id { get; set; }
        public string qrCode_shop { get; set; }
        public string deviceId { get; set; }
        public string serviceId { get; set; }
        public string characteristicId { get; set; }
    }
}
