//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_wares
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id { get; set; }
        public Nullable<int> num { get; set; }
        public string cloth { get; set; }
        public string norms { get; set; }
        public string type { get; set; }
        public string mark1 { get; set; }
        public string mark2 { get; set; }
        public string mark3 { get; set; }
        public string mark4 { get; set; }
        public string mark5 { get; set; }
    }
}
