//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeng_user
    {
        public string userName { get; set; }
        public string password { get; set; }
        public string power { get; set; }
        public string shop { get; set; }
        public int id { get; set; }
        public string qrCode_shop { get; set; }
        public string deviceId { get; set; }
        public string serviceId { get; set; }
        public string characteristicId { get; set; }
    }
}
