//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhangfengliang2025_rukumingxi
    {
        public int id { get; set; }
        public Nullable<System.DateTime> 入库日期 { get; set; }
        public string 入库人 { get; set; }
        public string 产品编号 { get; set; }
        public string 产品名称 { get; set; }
        public string 规格 { get; set; }
        public Nullable<int> 数量 { get; set; }
    }
}
