//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhangfengliang2025_kucun
    {
        public int id { get; set; }
        public Nullable<int> 产品编号 { get; set; }
        public string 产品名称 { get; set; }
        public string 规格 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
    }
}
