//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhangfengliang2025_daili
    {
        public int id { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public Nullable<int> D { get; set; }
        public string E { get; set; }
    }
}
