//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zheng_020826_userInfo
    {
        public int id { get; set; }
        public int game_id { get; set; }
        public System.DateTime time { get; set; }
        public string number { get; set; }
    }
}
