//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Personnel.HrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zheng_020826_gameInfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public int space { get; set; }
        public int model_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> game_top { get; set; }
    }
}
